### ISSUE TITLE
修饰符.native的作用

### ISSUE THREAD

**Issue by Coder-Li** [RunAndRun/vueDemo#1]
看到你在focusNews组件中使用backToTop组件，然后绑定click用了修饰符native，看了下官方文档不是很理解native的作用，可以谈谈您的理解吗？帮助我理解下（顺便提一句，项目对我很有帮助xD）

**Comment by RunAndRun** [comment]
我大概说下自己的理解 :  父组件(focusNews)中只能监听子组件(backToTop)的事件,  而事件的触发要在子组件(backToTop)中. 
如果没有这个修饰符, 那么只是在父组件中监听了click事件, 但是click事件触发不了,也就不会执行back(); 
native,应该算是语法糖吧.  加上了就相当于是在子组件的根节点上监听了事件.   
其实原理还是跟自定义事件是一样的.
我也是自己学的,工作还没有. 这也只是我自己目前的理解, 不保证正确.
这个demo如果能帮到你,我也很高兴.

**Comment by Coder-Li** [comment]
看你的意思我觉得这个语法糖是不是这样的，子组件监听到click事件后，在emit一个click事件给父组件，所以说用native可以直接调用父组件的method了，不然就只能调用子组件的method
刚上班不久，也是在深入学习vue框架，共同加油！

**Comment by RunAndRun** [comment]
加油!   
咋找的工作,说说经验呗 .   呵呵...

**Comment by Coder-Li** [comment]
你在哪？我在北京做的前端。
你这个水平可以直接上手前端vue项目的，估计es6特性和js基础掌握的差不多就ok了吧。拿着作品让他们hr看下应该没问题
求职类app多找找

**Comment by RunAndRun** [comment]
有时间吗  加个qq聊下  给我讲讲?  可以么  840430624

**Comment by Coder-Li** [comment]
ok
858582381
